name: Debug

on:
  pull_request:
    branches:
      - 'main'
      - '!renovate/**'

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      PATH: '$HOME/.fly/bin:$PATH'
      VERSION: '${{ inputs.version || steps.env-info.outputs.git-revision }}'
    steps:
      - run: |
          echo ${PATH}
          echo ${VERSION}
