name: Debug wbfy
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  debug-wbfy:
    runs-on: 'ubuntu-latest'
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -X POST -d '{"head":"wbfy","base":"main","title":"chore: wbfy this repo"}' || true
