name: Debug

on:
  pull_request:
    branches:
      - 'main'
      - '!renovate/**'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${PATH}
          echo ${VERSION}
