name: Debug

on:
  pull_request:
    branches:
      - 'main'
      - '!renovate/**'
  push:
    branches:
      - 'main'
      - 'renovate/**'

jobs:
  debug:
    runs-on: ['self-hosted', 'large']
    steps:
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
          if command -v python &> /dev/null; then echo "python: $(python --version)"; fi
          if command -v poetry &> /dev/null; then echo "poetry: $(poetry -v)"; fi
          if command -v gcloud &> /dev/null; then echo "gcloud: $(gcloud -v 2>&1 | head -n 1)"; fi
          if [[ "$(yarn -v)" == "1."* ]]; then echo "::set-output name=yarn-dir::$(yarn cache dir)"; fi
          echo "::set-output name=git-revision::$(git describe --always --tags)"
