name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUBLIC_GH_BOT_PAT }}
      - run: |
          echo "${{ github.event.repository.private }}"
          echo "${{ toJSON(fromJSON('["self-hosted", "large", github.event.repository.private]')) }}"
