name: Debug

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - '!renovate/**'

jobs:
  detect-node-version-matrix:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.detect-node-version-matrix.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - run: npx -y semver
      - id: detect-node-version-matrix
        run: |
          CONSTRAINT=$(node -e "console.log(((require('./package.json') || {}).engines || {}).node)")
          echo $CONSTRAINT
          npx -y semver -r $CONSTRAINT 12.0.0 14.0.0 16.0.0
          npx -y semver -r $CONSTRAINT 12.0.0 14.0.0 16.0.0 | xargs | sed 's/ /","/g' | sed 's/\.0\.0//g'
          NODE_VERSIONS=$(npx -y semver -r $CONSTRAINT 12.0.0 14.0.0 16.0.0 | xargs | sed 's/ /","/g' | sed 's/\.0\.0//g')
          echo $NODE_VERSIONS
          if [[ ! -z "$NODE_VERSIONS" ]]; then
            NODE_VERSIONS_JSON=$(echo "\"[\"$NODE_VERSIONS\"]\"")
            echo "::set-output name=json::$NODE_VERSIONS_JSON"
          fi
  test:
    uses: WillBooster/reusable-workflows/.github/workflows/test.yml@node-version
    needs: detect-node-version-matrix
    with:
      non_self_hosted: true
      node_version_matrix_json: ${{ needs.detect-node-version-matrix.outputs.json }}
  debug:
    runs-on: ubuntu-latest
    needs: detect-node-version-matrix
    strategy:
      matrix:
        # c.f. https://github.community/t/reusable-workflow-with-strategy-matrix/205676
        node-version: ${{ fromJson(needs.detect-node-version-matrix.outputs.json || '[""]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "${{ matrix.node-version }}"
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
          if command -v python &> /dev/null; then echo "python: $(python --version)"; fi
          if command -v poetry &> /dev/null; then echo "poetry: $(poetry -v)"; fi
          if command -v gcloud &> /dev/null; then echo "gcloud: $(gcloud -v 2>&1 | head -n 1)"; fi
          if [[ "$(yarn -v)" == "1."* ]]; then
            echo "::set-output name=yarn-dir::$(yarn cache dir)"
          fi
          echo "::set-output name=git-revision::$(git describe --always --tags)"
      - name: Set environment variables
        run: |
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV
          echo "VERSION=${{ steps.env-info.outputs.git-revision }}" >> $GITHUB_ENV
      - name: Verify environment variables
        run: |
          echo ${PATH}
          echo ${VERSION}

      - id: get-ver
        run: |
          if ! [[ -f .tool-versions ]]; then
            echo "::set-output name=node::$(cat .node-version || echo 16)"
          fi
      - if: ${{ matrix.node-version || steps.get-ver.outputs.node }}
        run: echo ${{ matrix.node-version || steps.get-ver.outputs.node }}

      - run: echo ${{ needs.detect-node-version-matrix.outputs.json || '[""]' }}
