name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ secrets.PUBLIC_GH_BOT_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/WillBooster/wbfy/pulls \
            -X POST -d '{"head":"wbfy","base":"main","title":"chore: wbfy this repo"}' || true
