name: Deploy app on staging

on:
  workflow_call:
    inputs:
      deploy_command:
        required: false
        type: string
      server_url:
        required: false
        type: string
    secrets:
      discord_webhook_url:
        required: false
      gcp_sa_key_json:
        required: false

jobs:
  deploy:
    uses: WillBooster/reusable-workflows/.github/workflows/deploy-common.yml@main
    with:
      deploy_command: ${{ inputs.deploy_command }}
      environment: staging
      server_url: ${{ inputs.server_url }}
    secrets:
      discord_webhook_url: ${{ secrets.discord_webhook_url }}
      gcp_sa_key_json: ${{ secrets.gcp_sa_key_json }}
