name: Show a given text

on:
  workflow_call:
    inputs:
      cpu_type:
        required: false
        type: string
      self_hosted:
        required: false
        type: boolean
      text:
        required: true
        type: string
    outputs:
      text:
        value: ${{ jobs.echo.outputs.text }}

jobs:
  echo:
    runs-on: ${{ (!github.event.repository.private && !self_hosted && 'ubuntu-latest') || (cpu_type == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (cpu_type == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    outputs:
      text: ${{ steps.echo.outputs.text }}
    steps:
      - uses: actions/checkout@v2
      - uses: willbooster/asdf-actions/install@main
      - id: echo
        run: |
          echo "::set-output name=text::${{ inputs.text }}"
