name: Show a given text

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string

jobs:
  train:
    runs-on: [self-hosted, large]
    steps:
      - uses: actions/checkout@v2
      - uses: willbooster/asdf-actions/install@main
      - run: echo ${{ inputs.text }}
