name: Show a given text

on:
  workflow_call:
    inputs:
      non_self_hosted:
        required: false
        type: boolean
      text:
        required: true
        type: string

jobs:
  echo:
    runs-on: ${{ (inputs.non_self_hosted && 'ubuntu-latest') || ['self-hosted', 'large'] }}
    steps:
      - uses: actions/checkout@v2
      - uses: willbooster/asdf-actions/install@main
      - run: echo ${{ inputs.text }}
