name: Release

on:
  workflow_call:
    inputs:
      dot_env_path:
        required: false
        type: string
      non_self_hosted:
        required: false
        type: boolean
    secrets:
      dot_env:
        required: false
      github_token:
        required: true

jobs:
  release:
    if: ${{ github.event.head_commit.author.username != 'renovate-bot' && github.event.head_commit.author.username != 'renovate[bot]' }}
    runs-on: ${{ (inputs.non_self_hosted && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/checkout@v2
      - if: ${{ inputs.dot_env_path }}
        run: echo "${{ secrets.dot_env }}" > ${{ inputs.dot_env_path }}

      - uses: willbooster/asdf-actions/install@main
      - name: Show environment information
        id: env-info
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
          if [[ "$(yarn -v)" == "1."* ]]; then
            echo "::set-output name=yarn-dir::$(yarn cache dir)"
          fi

      - if: ${{ steps.env-info.outputs.yarn-dir }}
        uses: actions/cache@v2
        with:
          path: ${{ steps.env-info.outputs.yarn-dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-
      - uses: actions/cache@v2
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-

      - run: yarn install
      - name: Release
        run: yarn semantic-release
        env: # existing GITHUB_TOKEN cannot fire release (published) event, so we need a personal token
          GITHUB_TOKEN: ${{ secrets.github_token }}
