name: Sync

on:
  workflow_call:
    inputs:
      non_self_hosted:
        required: false
        type: boolean
      sync_params_without_dest:
        required: false
        type: string
    secrets:
      DEST_GIT_URL:
        required: true

jobs:
  sync:
    # Make this workflow not work on other organizations for safety
    if: ${{ github.repository_owner == 'WillBooster' }}
    runs-on: ${{ (inputs.non_self_hosted && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    steps:
      # Because one-way-git-sync requires full history
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # We prefer actions/setup-node to asdf because asdf is slow on GitHub runners
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: asdf local nodejs system || true
      - name: Show environment information
        run: |
          echo "node: $(node -v)"

      - run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
      - run: |
          npx -y one-way-git-sync \
            ${{ inputs.sync_params_without_dest }} \
            -d ${{ secrets.DEST_GIT_URL }}
