name: Sync
on:
  push:
    branches:
      - main
jobs:
  sync:
    uses: WillBooster/reusable-workflows/.github/workflows/sync.yml@main
    with:
      sync_params_without_dest: '-v -i node_modules -i renovate.json'
    secrets:
      DEST_GIT_URL: git@github.com:WillBoosterLab/reusable-workflows.git
