name: Willboosterify
on:
  workflow_call:
    inputs:
      cpu_arch:
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  wbfy:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    runs-on: ${{ ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || (inputs.cpu_arch == 'X64' && fromJSON('["self-hosted", "large", "X64"]')) || (inputs.cpu_arch == 'ARM64' && fromJSON('["self-hosted", "large", "ARM64"]')) || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/checkout@v3
        # To trigger other workflows when running 'git push'
        with:
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ inputs.dot_env_path }}
        run: echo "${{ secrets.DOT_ENV }}" > ${{ inputs.dot_env_path }}

      # We prefer actions/setup-node to asdf because asdf is slow on GitHub runners
      # However, we must use asdf if .tool-versions since it may install some tools other than Node.js
      - name: Get Node.js version
        id: get-ver
        run: |
          if [[ -f .tool-versions ]] || [[ -f .node-version ]]; then
            echo "::set-output name=exist-version::1";
          fi
      - if: ${{ steps.get-ver.outputs.exist-version }}
        uses: willbooster/asdf-actions/install@main
      - uses: actions/setup-node@v3
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
          if [[ "$(yarn -v)" == "1."* ]]; then
            echo "::set-output name=yarn-dir::$(yarn cache dir)"
          fi

      - uses: actions/cache@v3
        with:
          path: .yarn
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-

      - run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs > wbfy.temp.json

          cat > wbfy.temp.js << EOF
          const actions = require('./wbfy.temp.json');
          for (const run of actions?.workflow_runs ?? []) {
            if (run.name !== 'Test') continue;
            if (run.head_branch !== 'wbfy') continue;

            if (run.status !== 'completed') break;
            if (run.conclusion === 'success') {
            console.log('merge');
          } else if (run.conclusion === 'failure') {
            console.log('pr');
          }
            break;
          }
          EOF

          COMMAND=$(node wbfy.temp.js)
          echo $COMMAND
          if [[ $COMMAND == "merge" ]]; then echo yeah1; fi
          if [[ $COMMAND == "pr" ]]; then echo yeah2; fi
