name: Willboosterify
on:
  workflow_call:
jobs:
  wbfy:
    runs-on: ${{ (inputs.non_self_hosted && 'ubuntu-latest') || fromJSON('["self-hosted", "large"]') }}
    steps:
      - uses: actions/checkout@v2
      - if: ${{ inputs.dot_env_path }}
        run: echo "${{ secrets.DOT_ENV }}" > ${{ inputs.dot_env_path }}

      # We prefer actions/setup-node to asdf because asdf is slow on GitHub runners
      # However, we must use asdf if .tool-versions since it may install some tools other than Node.js
      - id: get-ver
        run: |
          if [[ -f .tool-versions ]]; then
            echo "::set-output name=exist-tool-versions::1";
          fi
          if [[ "$(cat .tool-versions)" != *"node"* ]]; then
            echo "::set-output name=node::$(cat .node-version || echo 16)";
          fi
      - if: ${{ steps.get-ver.outputs.exist-tool-versions }}
        uses: willbooster/asdf-actions/install@main
      - if: ${{ steps.get-ver.outputs.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-ver.outputs.node }}
      - if: ${{ steps.get-ver.outputs.node }}
        run: |
          asdf plugin add nodejs || true
          asdf plugin add yarn || true
          asdf local nodejs system && asdf local yarn system
          if [[ ! $(yarn --version) ]]; then
            asdf install yarn 1.22.17 && asdf local yarn 1.22.17
          fi
      - name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
          if [[ "$(yarn -v)" == "1."* ]]; then
            echo "::set-output name=yarn-dir::$(yarn cache dir)"
          fi

      - uses: actions/cache@v2
        with:
          path: .yarn
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-berry-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-berry-

      - run: yarn install
      - run: yarn dlx wbfy .
      - run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
          git checkout -B wbfy
          git add -A
          git commit -m "chore: wbfy this repo"
          git push -f
          curl -u "WillBooster-bot:${{ secrets.GH_TOKEN }}" -X POST \
            -d '{"title":"chore: wbfy this repo","base":"main", "head":"wbfy"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls || true
